
DECLARE @STR VARCHAR(100) = 'PAYPALISHIRING'
DECLARE @ORIGINAL_OUTPUT VARCHAR(100) = 'PAHNAPLSIIGYIR'
DECLARE @OUTPUT VARCHAR(100) = ''
DECLARE @STR_LENGTH INT = LEN(@STR)
DECLARE @TBL_STR TABLE(ID INT IDENTITY PRIMARY KEY, LETTER VARCHAR(1))
DECLARE @ROWS INT = 3
DECLARE @COLUMN_INDEX INT = 0
DECLARE @DIRECTION BIT = 1

;WITH createstrtable(POS, LETTER) AS (
	SELECT [POS] = 1,
			[LETTER] = SUBSTRING(@STR, 1, 1)
	UNION ALL
	SELECT [POS] = POS + 1,
			[LETTER] = SUBSTRING(@STR, (POS + 1), 1)
	FROM CreateStrTable
	WHERE POS < @STR_LENGTH
)

--SELECT * 
--FROM createstrtable

, zigzagstr(POS, ORIGINAL_POS, DIRECTION, LETTER, COLUMN_INDEX) AS (
	SELECT 0,
			0,
			[DIRECTION] = @DIRECTION,
			[LETTER] = '',
			[COLUMN_INDEX] = @COLUMN_INDEX
	UNION ALL
	SELECT [POS] = zstr.POS + 1,
			[ORIGINAL_POS] = str.POS,
			[DIRECTION] = CASE 
								WHEN DIRECTION = 1 AND zstr.COLUMN_INDEX = @ROWS - 1 THEN ~DIRECTION
								WHEN DIRECTION = 0 AND zstr.COLUMN_INDEX = 2 THEN ~DIRECTION
								ELSE DIRECTION 
						END,
			[LETTER] = str.LETTER,
			[COLUMN_INDEX] = CASE WHEN DIRECTION = 1 THEN COLUMN_INDEX + 1
									ELSE COLUMN_INDEX - 1
							END
	FROM zigzagstr zstr
	JOIN createstrtable str
	ON	str.POS = zstr.POS + 1
	WHERE zstr.POS < @STR_LENGTH
)

--SELECT *
--FROM zigzagstr str
--WHERE POS > 0

--SELECT @OUTPUT = CONCAT(@OUTPUT, LETTER)
--FROM zigzagstr str
--WHERE POS > 0
--ORDER BY COLUMN_INDEX, ORIGINAL_POS

--SELECT @OUTPUT

--SELECT CASE WHEN @ORIGINAL_OUTPUT = @OUTPUT THEN 1
--			ELSE 0
--		END
