
DECLARE @STR VARCHAR(100) = 'PAYPALISHIRING'
DECLARE @STR_LENGTH INT = LEN(@STR)
DECLARE @TBL_STR TABLE(ID INT IDENTITY PRIMARY KEY, LETTER VARCHAR(1))
DECLARE @ROWS INT = 3
DECLARE @TBL_OUTPUT TABLE(ID INT IDENTITY PRIMARY KEY, COLUMN1 CHAR, COLUMN2 CHAR, COLUMN3 CHAR, LASTCOLUMN INT)

;WITH createstrtable(POS, LETTER) AS (
	SELECT [POS] = 1,
			[LETTER] = SUBSTRING(@STR, 1, 1)
	UNION ALL
	SELECT [POS] = POS + 1,
			[LETTER] = SUBSTRING(@STR, (POS + 1), 1)
	FROM CreateStrTable
	WHERE POS < @STR_LENGTH
)
, rows AS (
	SELECT POS,
			LETTER,
			[ROW] = CASE WHEN ROW_NUMBER() OVER(ORDER BY POS) <= @ROWS THEN 1
						 ELSE CEILING(CONVERT(DECIMAL(12, 2), ROW_NUMBER() OVER(ORDER BY POS)) / CONVERT(DECIMAL(12, 2), @ROWS))
					END
	FROM createstrtable
)
, rowsandcolumns AS (
	SELECT *,
			[COLUMN] = ROW_NUMBER() OVER(PARTITION BY ROW ORDER BY POS)
	FROM rows
)
SELECT COLUMN1, COLUMN2, COLUMN3
FROM rowsandcolumns RC
PIVOT (
	LETTER
	FOR [LETTER]
	IN ([1], [2], [3])
)
AS PIVOTTABLE